"use client";

import { useEffect, useState } from "react";

import { API, readJson } from "../../api-client";
type Application={id:number;user_id:number;email:string;display_name:string;handle:string;bio?:string|null;status:string;verification_status:string;submitted_at?:string|null;reviewed_at?:string|null;review_reason?:string|null};

export default function AdminVerificationsPage(){
 const [items,setItems]=useState<Application[]>([]); const [error,setError]=useState(""); const [busy,setBusy]=useState<number|null>(null);
 async function load(){const t=localStorage.getItem("lollipop_access_token");if(!t){location.href="/login";return}const r=await fetch(API+"/api/v1/admin/creator-applications",{headers:{Authorization:"Bearer "+t}});if(r.status===401){localStorage.removeItem("lollipop_access_token");location.href="/login";return}if(r.status===403){setError("Administrator access required.");return}const d=await readJson(r);if(!r.ok){setError(d.detail??"Could not load verification queue.");return}setItems(d)}
 useEffect(()=>{load()},[]);
 async function review(id:number,action:"approve"|"reject"){const t=localStorage.getItem("lollipop_access_token");if(!t)return;const reason=action==="reject"?window.prompt("Rejection reason (required):"):window.prompt("Review note (optional):");if(action==="reject"&&!reason)return;setBusy(id);setError("");const r=await fetch(API+`/api/v1/admin/creator-applications/${id}/${action}`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+t},body:JSON.stringify({reason:reason||null})});const d=await readJson(r);if(!r.ok)setError(d.detail??"Review failed.");else setItems(items.filter(x=>x.id!==id));setBusy(null)}
 return <main className="shell page"><nav className="nav"><a className="brand" href="/">◉ LOLLIPOP</a><div className="nav-links"><a href="/account">Account</a><a href="/discover">Discover</a></div></nav><header className="page-header"><p className="eyebrow">ADMIN · VERIFICATION</p><h1>Creator<br/><span>queue.</span></h1><p>Review submitted creator applications. Approval changes the account to the CREATOR role.</p></header>{error&&<p className="error">{error}</p>}<section className="admin-queue">{items.length===0?<div className="auth-card"><p className="eyebrow">QUEUE CLEAR</p><h2>No pending applications.</h2></div>:items.map(item=><article className="admin-card" key={item.id}><div className="admin-card-head"><div><p className="eyebrow">APPLICATION #{item.id}</p><h2>{item.display_name}</h2><p>@{item.handle} · {item.email}</p></div><strong>{item.verification_status}</strong></div>{item.bio&&<p className="admin-bio">{item.bio}</p>}<p className="admin-date">Submitted {item.submitted_at?new Date(item.submitted_at).toLocaleString():"—"}</p><div className="admin-actions"><button className="primary-button" disabled={busy===item.id} onClick={()=>review(item.id,"approve")}>Approve</button><button className="secondary-button" disabled={busy===item.id} onClick={()=>review(item.id,"reject")}>Reject</button></div></article>)}</section></main>
}
